from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import PlainTextResponse
from prometheus_client import generate_latest

from . import _metrics as metrics

router = APIRouter(
    tags=["metrics", "prometheus"],
    responses={404: {"description": "Not found"}},
)


# note: we expose this via a route as the prometheus asgi app
# cannot be mounted such that url_for("prometheus_metrics") can be used
# this seems to be a limitation of starlette
@router.get("/metrics", name="prometheus_metrics")
def get_metrics() -> PlainTextResponse:
    """Endpoint to expose prometheus metrics generated by the HTCondor Dashboard"""
    metrics.load()
    return PlainTextResponse(generate_latest())
