from __future__ import annotations

from fastapi import APIRouter

router = APIRouter(
    tags=["metrics", "prometheus"],
    responses={404: {"description": "Not found"}},
)


@router.get("/metrics")
def get_metrics() -> str:
    """Endpoint to expose prometheus metrics generated by the HTCondor Dashboard"""
    return "TODO: implement prometheus metrics endpoint"
